### ISSUE TITLE
Request to license the content 

### ISSUE THREAD

**Issue by JamesABaker** [cran-task-views/Epidemiology#24]
Hi there,
We would like to fork the repo and suggest some contributions. Would you consider adding a license that would allow us to do this?
Cheers :)

**Comment by zeileis** [comment]
The task views are clearly intended for this, see: https://github.com/cran-task-views/ctv/blob/main/Contributing.md

But you are right that we haven't explicitly adopted a license for the task views. I'll discuss this with my fellow task view editors (for all task views, not just this one) and also with the CRAN team. This will take some time, though.

In any case, there should not be an individual license for this task view but a unified solution. Hence I'm closing this issue here.

**Comment by JamesABaker** [comment]
Great! An all encompassing license sounds like it would be ideal.
